### ISSUE TITLE
Edge Warns

### ISSUE THREAD

**Issue by AxDSan** [b1ack0wl/Edge0day.exe#3]
Edge does warns you...

![](https://i.imgur.com/gSWnrMo.png)

**Comment by b1ack0wl** [comment]
Read the last line ;)

https://raw.githubusercontent.com/b1ack0wl/Edge0day.exe/master/README.md

**Comment by AxDSan** [comment]
> Read the last line ;)
> 
> https://raw.githubusercontent.com/b1ack0wl/Edge0day.exe/master/README.md

Fell right into it, LEMAO, you should make CTF challenges lol!
